# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nn.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 470)
        Form.setMinimumSize(QtCore.QSize(600, 470))
        Form.setMaximumSize(QtCore.QSize(600, 470))
        Form.setBaseSize(QtCore.QSize(600, 470))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ac-nn.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.background = QtWidgets.QFrame(Form)
        self.background.setGeometry(QtCore.QRect(-11, -11, 651, 561))
        self.background.setStyleSheet("QFrame#background {\n"
"background-color: rgb(25, 25, 25);\n"
"}")
        self.background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background.setObjectName("background")
        self.tabWidget = QtWidgets.QTabWidget(self.background)
        self.tabWidget.setGeometry(QtCore.QRect(20, 30, 581, 301))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"    background: rgb(29, 29, 29);\n"
"    border: 2px solid #d5e522;\n"
"    position: absolute;\n"
"    top: 0.5em;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    color: #FFFFFF;\n"
"    background: rgb(30, 30, 30);\n"
"    border: 2px solid #d5e522;\n"
"    border-bottom-color: #d5e522; \n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    min-width: 8ex;\n"
"    padding: 2px;\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"QTabBar::tab::selected {\n"
"    margin-bottom: 4px;\n"
"}\n"
"")
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Mouse = QtWidgets.QWidget()
        self.Mouse.setEnabled(True)
        self.Mouse.setAccessibleName("")
        self.Mouse.setAutoFillBackground(False)
        self.Mouse.setObjectName("Mouse")
        self.groupBox = QtWidgets.QGroupBox(self.Mouse)
        self.groupBox.setGeometry(QtCore.QRect(50, 50, 191, 121))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    color: #FFFFFF;\n"
"    background: rgb(25, 25, 25);\n"
"    border: 2px solid #d5e522\n"
"}")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 20, 171, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.seconds = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setBold(False)
        font.setWeight(50)
        self.seconds.setFont(font)
        self.seconds.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #d5e522;\n"
"    color: #FFFFFF;\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.seconds.setClearButtonEnabled(False)
        self.seconds.setObjectName("seconds")
        self.horizontalLayout.addWidget(self.seconds)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: #FFFFFF;\n"
"}")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.groupBox_2 = QtWidgets.QGroupBox(self.Mouse)
        self.groupBox_2.setGeometry(QtCore.QRect(320, 50, 191, 121))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    color: #FFFFFF;\n"
"    background: rgb(25, 25, 25);\n"
"    border: 2px solid #d5e522\n"
"}")
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(10, 20, 138, 91))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.radioButtonRepeat = QtWidgets.QRadioButton(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(10)
        self.radioButtonRepeat.setFont(font)
        self.radioButtonRepeat.setStyleSheet("QRadioButton { \n"
"    color: #FFFFFF;\n"
"}")
        self.radioButtonRepeat.setObjectName("radioButtonRepeat")
        self.verticalLayout_7.addWidget(self.radioButtonRepeat)
        self.radioButtonRepeatUntil = QtWidgets.QRadioButton(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(10)
        self.radioButtonRepeatUntil.setFont(font)
        self.radioButtonRepeatUntil.setStyleSheet("QRadioButton { \n"
"    color: #FFFFFF;\n"
"}")
        self.radioButtonRepeatUntil.setChecked(True)
        self.radioButtonRepeatUntil.setObjectName("radioButtonRepeatUntil")
        self.verticalLayout_7.addWidget(self.radioButtonRepeatUntil)
        self.spinBoxRepeat = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBoxRepeat.setGeometry(QtCore.QRect(80, 30, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        self.spinBoxRepeat.setFont(font)
        self.spinBoxRepeat.setStyleSheet("QSpinBox {\n"
"    border: 1px solid #d5e522;\n"
"    color: #FFFFFF;\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.spinBoxRepeat.setMinimum(1)
        self.spinBoxRepeat.setMaximum(99999)
        self.spinBoxRepeat.setObjectName("spinBoxRepeat")
        self.groupBox_3 = QtWidgets.QGroupBox(self.Mouse)
        self.groupBox_3.setGeometry(QtCore.QRect(50, 180, 461, 61))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("QGroupBox {\n"
"    color: #FFFFFF;\n"
"    background: rgb(25, 25, 25);\n"
"    border: 2px solid #d5e522\n"
"}")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 19, 441, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    color: #FFFFFF;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.mouseButton = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        self.mouseButton.setFont(font)
        self.mouseButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mouseButton.setStyleSheet("QComboBox {\n"
"    border: 1px solid #d5e522;\n"
"    color: #FFFFFF;\n"
"    background-color: rgb(30, 30, 30);\n"
"}\n"
"\n"
"QComboBox::hover {\n"
"    background-color: rgb(32, 32, 32);\n"
"}")
        self.mouseButton.setMaxCount(2)
        self.mouseButton.setObjectName("mouseButton")
        self.mouseButton.addItem("")
        self.mouseButton.addItem("")
        self.horizontalLayout_3.addWidget(self.mouseButton)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Mouse)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(49, 9, 461, 35))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TitleMouse = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(20)
        self.TitleMouse.setFont(font)
        self.TitleMouse.setStyleSheet("QLabel {\n"
"    color: #FFFFFF;\n"
"}")
        self.TitleMouse.setAlignment(QtCore.Qt.AlignCenter)
        self.TitleMouse.setObjectName("TitleMouse")
        self.verticalLayout.addWidget(self.TitleMouse)
        self.tabWidget.addTab(self.Mouse, "")
        self.Keyboard = QtWidgets.QWidget()
        self.Keyboard.setObjectName("Keyboard")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.Keyboard)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(50, 10, 461, 41))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TitleKeyboard = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.TitleKeyboard.setFont(font)
        self.TitleKeyboard.setStyleSheet("QLabel {\n"
"    color: #FFFFFF;\n"
"}")
        self.TitleKeyboard.setAlignment(QtCore.Qt.AlignCenter)
        self.TitleKeyboard.setObjectName("TitleKeyboard")
        self.verticalLayout_2.addWidget(self.TitleKeyboard)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.Keyboard)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(50, 49, 461, 91))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(18)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupChoiceKey = QtWidgets.QGroupBox(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setBold(True)
        font.setWeight(75)
        self.groupChoiceKey.setFont(font)
        self.groupChoiceKey.setStyleSheet("QGroupBox {\n"
"    color: #FFFFFF;\n"
"    background: rgb(25, 25, 25);\n"
"    border: 2px solid #d5e522\n"
"}")
        self.groupChoiceKey.setObjectName("groupChoiceKey")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupChoiceKey)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 441, 51))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelChooseKey = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelChooseKey.setFont(font)
        self.labelChooseKey.setStyleSheet("QLabel {\n"
"    color: #FFFFFF;\n"
"}")
        self.labelChooseKey.setObjectName("labelChooseKey")
        self.verticalLayout_3.addWidget(self.labelChooseKey)
        self.comboBoxKey = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        self.comboBoxKey.setFont(font)
        self.comboBoxKey.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBoxKey.setStyleSheet("QComboBox {\n"
"    border: 1px solid #d5e522;\n"
"    color: #FFFFFF;\n"
"    background-color: rgb(30, 30, 30);\n"
"}\n"
"\n"
"QComboBox::hover {\n"
"    background-color: rgb(32, 32, 32);\n"
"}")
        self.comboBoxKey.setObjectName("comboBoxKey")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.comboBoxKey.addItem("")
        self.verticalLayout_3.addWidget(self.comboBoxKey)
        self.horizontalLayout_5.addWidget(self.groupChoiceKey)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.Keyboard)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(50, 150, 461, 91))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(18)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBoxDelay = QtWidgets.QGroupBox(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxDelay.setFont(font)
        self.groupBoxDelay.setStyleSheet("QGroupBox {\n"
"    color: #FFFFFF;\n"
"    background: rgb(25, 25, 25);\n"
"    border: 2px solid #d5e522\n"
"}")
        self.groupBoxDelay.setObjectName("groupBoxDelay")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.groupBoxDelay)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 20, 201, 61))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel {\n"
"    color: #FFFFFF;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.betweenKeystrokes = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        self.betweenKeystrokes.setFont(font)
        self.betweenKeystrokes.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #d5e522;\n"
"    color: #FFFFFF;\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.betweenKeystrokes.setObjectName("betweenKeystrokes")
        self.verticalLayout_6.addWidget(self.betweenKeystrokes)
        self.horizontalLayout_6.addWidget(self.groupBoxDelay)
        self.groupBoxBetween = QtWidgets.QGroupBox(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxBetween.setFont(font)
        self.groupBoxBetween.setStyleSheet("QGroupBox {\n"
"    color: #FFFFFF;\n"
"    background: rgb(25, 25, 25);\n"
"    border: 2px solid #d5e522\n"
"}")
        self.groupBoxBetween.setObjectName("groupBoxBetween")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.groupBoxBetween)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(9, 20, 201, 61))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    color: #FFFFFF;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.betweenPressRelease = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        self.betweenPressRelease.setFont(font)
        self.betweenPressRelease.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #d5e522;\n"
"    color: #FFFFFF;\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.betweenPressRelease.setObjectName("betweenPressRelease")
        self.verticalLayout_5.addWidget(self.betweenPressRelease)
        self.horizontalLayout_6.addWidget(self.groupBoxBetween)
        self.tabWidget.addTab(self.Keyboard, "")
        self.groupBox_4 = QtWidgets.QGroupBox(self.background)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 339, 301, 81))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("QGroupBox {\n"
"    color: #FFFFFF;\n"
"    background: rgb(25, 25, 25);\n"
"    border: 2px solid #d5e522\n"
"}")
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_4)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 30, 281, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel {\n"
"    color: #FFFFFF;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.startChoiceButton = QtWidgets.QComboBox(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        self.startChoiceButton.setFont(font)
        self.startChoiceButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.startChoiceButton.setStyleSheet("QComboBox {\n"
"    border: 1px solid #d5e522;\n"
"    color: #FFFFFF;\n"
"    background-color: rgb(30, 30, 30);\n"
"}\n"
"\n"
"QComboBox::hover {\n"
"    background-color: rgb(32, 32, 32);\n"
"}")
        self.startChoiceButton.setObjectName("startChoiceButton")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.startChoiceButton.addItem("")
        self.horizontalLayout_4.addWidget(self.startChoiceButton)
        self.startButton = QtWidgets.QPushButton(self.background)
        self.startButton.setEnabled(True)
        self.startButton.setGeometry(QtCore.QRect(20, 430, 581, 41))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.startButton.setFont(font)
        self.startButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.startButton.setStyleSheet("QPushButton{\n"
"    color:  rgb(30, 30, 30);\n"
"    background-color: #d5e522;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color:#949e20;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    color: #97a314;\n"
"    background-color: rgb(28, 28, 28);\n"
"}")
        self.startButton.setObjectName("startButton")
        self.groupBox_5 = QtWidgets.QGroupBox(self.background)
        self.groupBox_5.setGeometry(QtCore.QRect(330, 340, 271, 81))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet("QGroupBox {\n"
"    color: #FFFFFF;\n"
"    background: rgb(25, 25, 25);\n"
"    border: 2px solid #d5e522\n"
"}")
        self.groupBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(10, 20, 251, 51))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.statusLabel = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.statusLabel.setFont(font)
        self.statusLabel.setStyleSheet("QLabel {\n"
"    color: #FFFFFF;\n"
"}")
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout_8.addWidget(self.statusLabel)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "AC-NN"))
        self.groupBox.setTitle(_translate("Form", "Click interval"))
        self.seconds.setPlaceholderText(_translate("Form", "example: 0,01"))
        self.label.setText(_translate("Form", "seconds"))
        self.groupBox_2.setTitle(_translate("Form", "Click repeat"))
        self.radioButtonRepeat.setText(_translate("Form", "Repeat"))
        self.radioButtonRepeatUntil.setText(_translate("Form", "Repeat until stopped"))
        self.groupBox_3.setTitle(_translate("Form", "Click Option"))
        self.label_2.setText(_translate("Form", "Mouse button:"))
        self.mouseButton.setItemText(0, _translate("Form", "Left"))
        self.mouseButton.setItemText(1, _translate("Form", "Right"))
        self.TitleMouse.setText(_translate("Form", "Mouse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Mouse), _translate("Form", "Mouse"))
        self.TitleKeyboard.setText(_translate("Form", "Keyboard"))
        self.groupChoiceKey.setTitle(_translate("Form", "Choose Key"))
        self.labelChooseKey.setText(_translate("Form", "Key:"))
        self.comboBoxKey.setItemText(0, _translate("Form", "Q"))
        self.comboBoxKey.setItemText(1, _translate("Form", "W"))
        self.comboBoxKey.setItemText(2, _translate("Form", "E"))
        self.comboBoxKey.setItemText(3, _translate("Form", "R"))
        self.comboBoxKey.setItemText(4, _translate("Form", "T"))
        self.comboBoxKey.setItemText(5, _translate("Form", "Y"))
        self.comboBoxKey.setItemText(6, _translate("Form", "U"))
        self.comboBoxKey.setItemText(7, _translate("Form", "I"))
        self.comboBoxKey.setItemText(8, _translate("Form", "O"))
        self.comboBoxKey.setItemText(9, _translate("Form", "P"))
        self.comboBoxKey.setItemText(10, _translate("Form", "A"))
        self.comboBoxKey.setItemText(11, _translate("Form", "S"))
        self.comboBoxKey.setItemText(12, _translate("Form", "D"))
        self.comboBoxKey.setItemText(13, _translate("Form", "F"))
        self.comboBoxKey.setItemText(14, _translate("Form", "G"))
        self.comboBoxKey.setItemText(15, _translate("Form", "H"))
        self.comboBoxKey.setItemText(16, _translate("Form", "J"))
        self.comboBoxKey.setItemText(17, _translate("Form", "K"))
        self.comboBoxKey.setItemText(18, _translate("Form", "L"))
        self.comboBoxKey.setItemText(19, _translate("Form", "Z"))
        self.comboBoxKey.setItemText(20, _translate("Form", "X"))
        self.comboBoxKey.setItemText(21, _translate("Form", "C"))
        self.comboBoxKey.setItemText(22, _translate("Form", "V"))
        self.comboBoxKey.setItemText(23, _translate("Form", "B"))
        self.comboBoxKey.setItemText(24, _translate("Form", "N"))
        self.comboBoxKey.setItemText(25, _translate("Form", "M"))
        self.comboBoxKey.setItemText(26, _translate("Form", "1"))
        self.comboBoxKey.setItemText(27, _translate("Form", "2"))
        self.comboBoxKey.setItemText(28, _translate("Form", "3"))
        self.comboBoxKey.setItemText(29, _translate("Form", "4"))
        self.comboBoxKey.setItemText(30, _translate("Form", "5"))
        self.comboBoxKey.setItemText(31, _translate("Form", "6"))
        self.comboBoxKey.setItemText(32, _translate("Form", "7"))
        self.comboBoxKey.setItemText(33, _translate("Form", "8"))
        self.comboBoxKey.setItemText(34, _translate("Form", "9"))
        self.comboBoxKey.setItemText(35, _translate("Form", "0"))
        self.comboBoxKey.setItemText(36, _translate("Form", "-"))
        self.comboBoxKey.setItemText(37, _translate("Form", "+"))
        self.comboBoxKey.setItemText(38, _translate("Form", "Space"))
        self.comboBoxKey.setItemText(39, _translate("Form", "Tab"))
        self.comboBoxKey.setItemText(40, _translate("Form", "Caps Lock"))
        self.comboBoxKey.setItemText(41, _translate("Form", "Esc"))
        self.comboBoxKey.setItemText(42, _translate("Form", "F1"))
        self.comboBoxKey.setItemText(43, _translate("Form", "F2"))
        self.comboBoxKey.setItemText(44, _translate("Form", "F3"))
        self.comboBoxKey.setItemText(45, _translate("Form", "F4"))
        self.comboBoxKey.setItemText(46, _translate("Form", "F5"))
        self.comboBoxKey.setItemText(47, _translate("Form", "F6"))
        self.comboBoxKey.setItemText(48, _translate("Form", "F7"))
        self.comboBoxKey.setItemText(49, _translate("Form", "F8"))
        self.comboBoxKey.setItemText(50, _translate("Form", "F9"))
        self.comboBoxKey.setItemText(51, _translate("Form", "F10"))
        self.comboBoxKey.setItemText(52, _translate("Form", "F11"))
        self.comboBoxKey.setItemText(53, _translate("Form", "F12"))
        self.groupBoxDelay.setTitle(_translate("Form", "Option of time between keystrokes"))
        self.label_5.setText(_translate("Form", "Time between keystrokes:"))
        self.betweenKeystrokes.setPlaceholderText(_translate("Form", "seconds(example: 0,01)"))
        self.groupBoxBetween.setTitle(_translate("Form", "Option of time"))
        self.label_3.setText(_translate("Form", "The time between \n"
"pressing and releasing the key:"))
        self.betweenPressRelease.setPlaceholderText(_translate("Form", "seconds(example: 0,01)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Keyboard), _translate("Form", "Keyboard"))
        self.groupBox_4.setTitle(_translate("Form", "Setting of start/stop"))
        self.label_4.setText(_translate("Form", "Start/Stop Key:"))
        self.startChoiceButton.setItemText(0, _translate("Form", "F1"))
        self.startChoiceButton.setItemText(1, _translate("Form", "F2"))
        self.startChoiceButton.setItemText(2, _translate("Form", "F3"))
        self.startChoiceButton.setItemText(3, _translate("Form", "F4"))
        self.startChoiceButton.setItemText(4, _translate("Form", "F5"))
        self.startChoiceButton.setItemText(5, _translate("Form", "F6"))
        self.startChoiceButton.setItemText(6, _translate("Form", "F7"))
        self.startChoiceButton.setItemText(7, _translate("Form", "F8"))
        self.startChoiceButton.setItemText(8, _translate("Form", "F9"))
        self.startChoiceButton.setItemText(9, _translate("Form", "F10"))
        self.startChoiceButton.setItemText(10, _translate("Form", "F11"))
        self.startChoiceButton.setItemText(11, _translate("Form", "F12"))
        self.startChoiceButton.setItemText(12, _translate("Form", "1"))
        self.startChoiceButton.setItemText(13, _translate("Form", "2"))
        self.startChoiceButton.setItemText(14, _translate("Form", "3"))
        self.startChoiceButton.setItemText(15, _translate("Form", "4"))
        self.startChoiceButton.setItemText(16, _translate("Form", "5"))
        self.startChoiceButton.setItemText(17, _translate("Form", "6"))
        self.startChoiceButton.setItemText(18, _translate("Form", "7"))
        self.startChoiceButton.setItemText(19, _translate("Form", "8"))
        self.startChoiceButton.setItemText(20, _translate("Form", "9"))
        self.startChoiceButton.setItemText(21, _translate("Form", "0"))
        self.startChoiceButton.setItemText(22, _translate("Form", "Q"))
        self.startChoiceButton.setItemText(23, _translate("Form", "W"))
        self.startChoiceButton.setItemText(24, _translate("Form", "E"))
        self.startChoiceButton.setItemText(25, _translate("Form", "R"))
        self.startChoiceButton.setItemText(26, _translate("Form", "T"))
        self.startChoiceButton.setItemText(27, _translate("Form", "Y"))
        self.startChoiceButton.setItemText(28, _translate("Form", "U"))
        self.startChoiceButton.setItemText(29, _translate("Form", "I"))
        self.startChoiceButton.setItemText(30, _translate("Form", "O"))
        self.startChoiceButton.setItemText(31, _translate("Form", "P"))
        self.startChoiceButton.setItemText(32, _translate("Form", "A"))
        self.startChoiceButton.setItemText(33, _translate("Form", "S"))
        self.startChoiceButton.setItemText(34, _translate("Form", "D"))
        self.startChoiceButton.setItemText(35, _translate("Form", "F"))
        self.startChoiceButton.setItemText(36, _translate("Form", "G"))
        self.startChoiceButton.setItemText(37, _translate("Form", "H"))
        self.startChoiceButton.setItemText(38, _translate("Form", "J"))
        self.startChoiceButton.setItemText(39, _translate("Form", "K"))
        self.startChoiceButton.setItemText(40, _translate("Form", "L"))
        self.startChoiceButton.setItemText(41, _translate("Form", "Z"))
        self.startChoiceButton.setItemText(42, _translate("Form", "X"))
        self.startChoiceButton.setItemText(43, _translate("Form", "C"))
        self.startChoiceButton.setItemText(44, _translate("Form", "V"))
        self.startChoiceButton.setItemText(45, _translate("Form", "B"))
        self.startChoiceButton.setItemText(46, _translate("Form", "N"))
        self.startChoiceButton.setItemText(47, _translate("Form", "M"))
        self.startButton.setText(_translate("Form", "Start waiting for the start/stop key"))
        self.groupBox_5.setTitle(_translate("Form", "Status"))
        self.statusLabel.setText(_translate("Form", "Status: Not started"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
